---EMPLOYEE MANAGEMENT SYSTEM

---CREATED TABLE DEPARTMENTS
CREATE TABLE DEPARTMENTS(
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50),
    LOCATION VARCHAR(50)
);

---CREATED  TABLE EMPLOYEES
CREATE TABLE EMPLOYEES(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    DEPT_ID INT,
    SALARY NUMERIC(10,2),
    MANAGER_ID INT,
    JOIN_DATE DATE,

    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENTS(DEPT_ID)
);

--CREATED TABLE PROJECTS
CREATE TABLE PROJECTS(
    PROJECT_ID INT PRIMARY KEY,
    PROJECT_NAME VARCHAR(100),
    BUDGET NUMERIC(12,2)
);

--CREATED TABLE EMPLOYEES_PROJECT
CREATE TABLE EMPLOYEE_PROJECT(
    EMP_ID INT,
    PROJECT_ID INT,

    FOREIGN KEY (EMP_ID)
    REFERENCES EMPLOYEES(EMP_ID),

    FOREIGN KEY (PROJECT_ID)
    REFERENCES PROJECTS(PROJECT_ID)
);

---IMPORTING DATA
COPY DEPARTMENTS(DEPT_ID,DEPT_NAME,LOCATION)
FROM 'D:\LEARN\posgresql\project 2\departments.csv'
DELIMITER ','
CSV HEADER;

COPY EMPLOYEES(EMP_ID,EMP_NAME,DEPT_ID,SALARY,MANAGER_ID,JOIN_DATE)
FROM 'D:\LEARN\posgresql\project 2\employees.csv'
DELIMITER ','
CSV HEADER;

COPY PROJECTS(PROJECT_ID,PROJECT_NAME,BUDGET)
FROM 'D:\LEARN\posgresql\project 2\projects.csv'
DELIMITER ','
CSV HEADER;

COPY EMPLOYEE_PROJECT(EMP_ID,PROJECT_ID)
FROM 'D:\LEARN\posgresql\project 2\employeeproject.csv'
DELIMITER ','
CSV HEADER;

---CHECKING TABLES
SELECT *
FROM DEPARTMENTS;

SELECT *
FROM EMPLOYEES

SELECT *
FROM PROJECTS;

SELECT *
FROM EMPLOYEE_PROJECT;

------Phase 1: Basic Business Queries

------Q1. Show all employees with department names

SELECT E.EMP_NAME,D.DEPT_NAME 
FROM EMPLOYEES E
JOIN 
DEPARTMENTS D
ON D.DEPT_ID=E.DEPT_ID;


------Q2. Show employees earning more than ₹70,000
SELECT *
FROM EMPLOYEES
WHERE SALARY>70000;

-----Q3. Total employees in each department

SELECT D.DEPT_NAME,COUNT(E.EMP_NAME)AS COUNT
FROM EMPLOYEES E
JOIN 
DEPARTMENTS D
ON D.DEPT_ID=E.DEPT_ID
GROUP BY D.DEPT_NAME;

---Q4. Average salary by department

SELECT D.DEPT_NAME,AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES E
JOIN 
DEPARTMENTS D
ON D.DEPT_ID=E.DEPT_ID
GROUP BY D.DEPT_NAME;

----Q5. Highest paid employee
SELECT EMP_NAME,SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1;

----Phase 2: Self Join 
----Q6. Employee and Manager Name
SELECT M.EMP_NAME AS MANAGER,E.EMP_NAME AS EMPLOYEE
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMP_ID;

-----Q7. Manager with most employees

SELECT M.EMP_NAME AS MANAGER, COUNT(E.EMP_NAME) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMP_ID
GROUP BY M.EMP_NAME
ORDER BY COUNT(E.EMP_NAME) DESC
LIMIT 1;

---Q8. Employees Working on More Than One Project
SELECT E.EMP_NAME,E.EMP_ID,COUNT(P.PROJECT_ID) AS PROJECT_COUNT
FROM EMPLOYEES E
JOIN EMPLOYEE_PROJECT P
ON E.EMP_ID=P.EMP_ID
GROUP BY E.EMP_ID,E.EMP_NAME
HAVING COUNT(PROJECT_ID)>1;

---Q9. Department with Highest Average Salary
SELECT D.DEPT_NAME,AVG(E.SALARY) AS AVERAGE_SALARY
FROM DEPARTMENTS D
JOIN 
EMPLOYEES E
ON D.DEPT_ID=E.DEPT_ID
GROUP BY D.DEPT_NAME
ORDER BY AVG(E.SALARY) DESC
LIMIT 1;

---Q10. Project with Highest Budget

SELECT PROJECT_NAME,BUDGET AS HIGHEST_BUDGET
FROM PROJECTS
ORDER BY BUDGET DESC
LIMIT 1;

---Q11. Total Salary Expense Per Department
SELECT D.DEPT_NAME,SUM(E.SALARY) AS TOTAL_EXPENSES
FROM DEPARTMENTS D
JOIN EMPLOYEES E
ON D.DEPT_ID=E.DEPT_ID
GROUP BY D.DEPT_NAME;

----Q12. Highest Paid Employee in Each Department

SELECT  D.DEPT_NAME,MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES E
JOIN 
DEPARTMENTS D
ON D.DEPT_ID=E.DEPT_ID
GROUP BY D.DEPT_NAME;


---Q13. Employees Earning Above Department Average
SELECT *
FROM EMPLOYEES E
WHERE SALARY>
(
SELECT AVG(SALARY)
FROM EMPLOYEES E
WHERE DEPT_ID=E.DEPT_ID
);

----Q14. Department-wise Employee Ranking

SELECT EMP_NAME,EMP_ID,DEPT_ID,
RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC)
FROM EMPLOYEES;

---Q15. Top 5 Highest Paid Employees
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

----Phase 4: CTE + Advanced Business Reports
---Q16. Top Salary Employee in Each Department 

WITH TOP_RANK AS
(
SELECT EMP_NAME,EMP_ID,SALARY,
RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RANKS
FROM EMPLOYEES
)
SELECT *
FROM TOP_RANK
WHERE RANKS=1;

--Q17. Department Salary Report

WITH  SALARY_REPORT AS
(
SELECT DEPT_ID,AVG(SALARY) AS AVERAGE_SALARY,
 SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT *
FROM SALARY_REPORT;

---Q18. Employees Above Company Average Salary
WITH COMPANY_AVERAGE AS
(
SELECT AVG(SALARY)AS AVERAGE_SALARY
FROM EMPLOYEES
)
SELECT *
FROM EMPLOYEES
WHERE SALARY>
(
SELECT *
FROM COMPANY_AVERAGE
);

---Q19. Department with Maximum Employees
SELECT D.DEPT_ID,D.DEPT_NAME,COUNT(E.EMP_ID) AS EMPLOYEES_COUNT
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPT_ID=D.DEPT_ID
GROUP BY D.DEPT_NAME,D.DEPT_ID
ORDER BY COUNT(E.EMP_ID) DESC
LIMIT 1;

----Q20. Project Assigned to Most Employees

SELECT P.PROJECT_NAME,COUNT(EP.EMP_ID) AS EMP_COUNT
FROM PROJECTS P
JOIN EMPLOYEE_PROJECT EP
ON P.PROJECT_ID = EP.PROJECT_ID
GROUP BY P.PROJECT_NAME
ORDER BY EMP_COUNT DESC
LIMIT 1;


